import type { EnvSchema } from "./schema.js";

/**
 * Build a `.env.example` document from schema keys only.
 * Never emits real values — placeholders are descriptive comments + empty assignments.
 */
export function generateEnvExample(schema: EnvSchema): string {
  const lines: string[] = [
    "# Generated by EnvDoctor — keys only, no secret values",
    "# Copy to .env and fill in real values locally (never commit .env)",
    "",
  ];

  const keys = Object.keys(schema).sort();
  for (const key of keys) {
    const field = schema[key];
    const parts: string[] = [];
    if (field.description) {
      parts.push(field.description);
    }
    parts.push(field.required ? "required" : "optional");
    if (field.kind === "url") {
      parts.push("url");
    }
    if (field.kind === "enum" && field.enum) {
      parts.push(`one of: ${field.enum.join("|")}`);
    }
    if (field.minLength !== undefined) {
      parts.push(`minLength=${field.minLength}`);
    }
    lines.push(`# ${parts.join(" · ")}`);
    lines.push(`${key}=`);
    lines.push("");
  }

  return lines.join("\n");
}
